- hosts: vps
  user: root
  tasks:
    - include_vars: vars.yaml

    - name: deploy code from github
      git: repo={{item.repo_url}} dest={{item.destination}} remote={{item.remote}} version={{item.branch}} accept_hostkey=yes
      loop:
        - { repo_url: 'https://github.com/peachcloud/peach-vps.git', remote: 'main', branch: 'main', destination: '{{src_dir}}/peach-vps' }

    - name: create nginx site configs
      action: template src={{item.template}} dest=/etc/nginx/sites-enabled/{{item.name}}
      loop:
        - { template: 'templates/nginx_peach.conf', name: 'peach.conf' }
      notify:
        - restart nginx

    - name: copy index.html
      action: template src=index.html dest=/srv/www/index.html
      notify:
        - restart nginx

    - name: restart server and webapp
      command: /bin/true
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted

