- hosts: vps
  user: root
  tasks:
    - include_vars: vars.yaml

    - name: Setup users and groups
      block:
      - name: Ensure groups exist
        group:
          name: peach
          state: present

      - name: Ensure users exist
        ansible.builtin.user:
          name: "{{ item }}"
          state: present
          groups: "peach"
        loop:
          - notplants
          - glyph

    - name: copy over ssh keys for deploy purposes
      action: copy src={{item.from}} dest={{item.to}} mode={{item.mode}}
      loop:
        - { from: 'secret_files/deploy_rsa.pub', to: '/root/.ssh/id_rsa.pub', mode: '0644' }
        - { from: 'secret_files/deploy_rsa', to: '/root/.ssh/id_rsa', mode: '0600' }

    - name: ensure log directory
      action: file dest={{log_dir}} state=directory

    - name: ensure src directory
      action: file dest={{src_dir}} state=directory

    - name: ensure www directory
      action: file dest=/srv/www state=directory

    - name: install packages
      apt:
        pkg:
          - git
          - nginx


